-- MySQL Script generated by MySQL Workbench
-- Tue Jun 30 11:48:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema expressFood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema expressFood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expressFood` DEFAULT CHARACTER SET utf8 ;
USE `expressFood` ;

-- -----------------------------------------------------
-- Table `expressFood`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressFood`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telephone` INT NOT NULL,
  `role` ENUM('Administrateur', 'Chef Cuisinier', 'Livreur', 'Client') NOT NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`InformationLivreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressFood`.`InformationLivreur` (
  `idStatutLivreur` INT NOT NULL AUTO_INCREMENT,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `temps` INT NOT NULL,
  `Statut` ENUM('En Livraison', 'Indisponible', 'Libre') NOT NULL,
  `UtilisateurIdUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idStatutLivreur`),
  CONSTRAINT `fk_StatutLivreur_Utilisateur1`
    FOREIGN KEY (`UtilisateurIdUtilisateur`)
    REFERENCES `expressFood`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_StatutLivreur_Utilisateur1_idx` ON `expressFood`.`InformationLivreur` (`UtilisateurIdUtilisateur` ASC) ;


-- -----------------------------------------------------
-- Table `expressFood`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressFood`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `rue` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `codePostal` INT NOT NULL,
  `etage` INT NULL,
  `batiment` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressFood`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressFood`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `dateCreation` DATETIME NOT NULL,
  `dateLivraison` DATETIME NOT NULL,
  `statutCommande` ENUM('En Attente', 'En Livraison', 'Livrer', 'Annulee') NOT NULL,
  `roleCommande` TINYINT NOT NULL,
  `paiement` TINYINT NOT NULL,
  `UtilisateurIdUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idCommande`),
  CONSTRAINT `fk_Commande_Utilisateur1`
    FOREIGN KEY (`UtilisateurIdUtilisateur`)
    REFERENCES `expressFood`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Commande_Utilisateur1_idx` ON `expressFood`.`Commande` (`UtilisateurIdUtilisateur` ASC) ;


-- -----------------------------------------------------
-- Table `expressFood`.`Plat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressFood`.`Plat` (
  `idPlat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `type` ENUM('Dessert', 'Plat Principale') NOT NULL,
  `platDuJour` TINYINT NOT NULL,
  `prix` FLOAT NOT NULL,
  `UtilisateurIdUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idPlat`),
  CONSTRAINT `fk_Plat_Utilisateur1`
    FOREIGN KEY (`UtilisateurIdUtilisateur`)
    REFERENCES `expressFood`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Plat_Utilisateur1_idx` ON `expressFood`.`Plat` (`UtilisateurIdUtilisateur` ASC) ;


-- -----------------------------------------------------
-- Table `expressFood`.`ClientAdresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressFood`.`ClientAdresse` (
  `UtilisateurIdUtilisateur` INT NOT NULL,
  `AdresseIdAdresse` INT NOT NULL,
  CONSTRAINT `fk_Utilisateur_has_Adresse_Utilisateur1`
    FOREIGN KEY (`UtilisateurIdUtilisateur`)
    REFERENCES `expressFood`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Adresse_Adresse1`
    FOREIGN KEY (`AdresseIdAdresse`)
    REFERENCES `expressFood`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Utilisateur_has_Adresse_Adresse1_idx` ON `expressFood`.`ClientAdresse` (`AdresseIdAdresse` ASC) ;

CREATE INDEX `fk_Utilisateur_has_Adresse_Utilisateur1_idx` ON `expressFood`.`ClientAdresse` (`UtilisateurIdUtilisateur` ASC) ;


-- -----------------------------------------------------
-- Table `expressFood`.`CommandePlat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressFood`.`CommandePlat` (
  `CommandeIdCommande` INT NOT NULL,
  `PlatIdPlat` INT NOT NULL,
  `quantite` INT NOT NULL,
  CONSTRAINT `fk_Commande_has_Plat_Commande1`
    FOREIGN KEY (`CommandeIdCommande`)
    REFERENCES `expressFood`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Plat_Plat1`
    FOREIGN KEY (`PlatIdPlat`)
    REFERENCES `expressFood`.`Plat` (`idPlat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Commande_has_Plat_Plat1_idx` ON `expressFood`.`CommandePlat` (`PlatIdPlat` ASC) ;

CREATE INDEX `fk_Commande_has_Plat_Commande1_idx` ON `expressFood`.`CommandePlat` (`CommandeIdCommande` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
